/**
 * PR Templates
 *
 * Templates for GitHub PR outreach by tier.
 */

import type { Config, Tier, Prospect } from "../types";

// =============================================================================
// PR Title
// =============================================================================

export const PR_TITLE = "Join the Bitcoin AI Agent Economy";

// =============================================================================
// PR Branch Name
// =============================================================================

export const PR_BRANCH = "aibtc/bitcoin-ai-invitation";

// =============================================================================
// AIBTC_INVITATION.md Content
// =============================================================================

export function generateInvitationFile(config: Config): string {
  return `# Join the Bitcoin AI Agent Economy

You've been invited to get your AI agents on Bitcoin.

## One-Command Install

\`\`\`bash
npx aibtc-cli install
\`\`\`

This installs:
- Stacks wallet (Bitcoin L2)
- Moltbot (autonomous AI agents)
- aibtc-yield skill (auto-earn ~5% on sBTC)

## What You Get

1. **Free sBTC** - Reply to the PR with your address
2. **Yield farming** - Your sBTC auto-deposits to Zest/Hermetica
3. **Agent capabilities** - Your AI can hold, send, and earn Bitcoin

## The Vision

Bitcoin is AI-native money. Your agents shouldn't need bank accounts or stablecoins. They should earn and spend sound money.

## Resources

- [AIBTC Documentation](${config.websiteLink})
- [Stacks/sBTC Overview](https://sbtc.tech)
- [Moltbot Skills](https://molthub.com)
- [Discord Community](${config.discordLink})

## Questions?

Book a call: ${config.calendlyLink}

---

*Powered by AIBTC - Bitcoin for AI Agents*
`;
}

// =============================================================================
// Tier A Template (Claude/MCP builders)
// =============================================================================

function tierAPRBody(
  username: string,
  repoName: string,
  personalizationHooks: string[],
  config: Config
): string {
  const hookText = personalizationHooks.length > 0
    ? personalizationHooks[0]
    : "your AI agent work";

  return `Hey @${username}! 👋

Your work on **${repoName}** caught our attention - ${hookText}.

We're building the **AI agent economy on Bitcoin** and want you in.

## What we're offering

Install \`aibtc-cli\` and get:
- **Free sBTC airdrop** to your new wallet
- **Moltbot** - autonomous AI agents that can hold and transact Bitcoin
- **aibtc-yield skill** - your agents auto-earn ~5% yield via Zest/Hermetica
- **One command** - everything installs together

## Quick Start

\`\`\`bash
npx aibtc-cli install
\`\`\`

That's it. The CLI:
1. Sets up your Stacks wallet
2. Installs Moltbot + aibtc-yield skill
3. Connects to yield protocols
4. Outputs your address for the airdrop

## Claim your sBTC

After install, reply to this PR with your Stacks address (starts with \`SP...\`).

We'll send sBTC within 24 hours. Your agents can start earning immediately.

## Why Bitcoin for AI agents?

Arthur Hayes thesis: Bitcoin is AI-native money. Agents need:
- Permissionless transactions (no bank accounts)
- Programmable money (smart contracts)
- Sound money (not inflatable stablecoins)

sBTC = Bitcoin on Stacks = agents can hold, earn, and spend BTC.

## This is legit

We know unsolicited PRs can feel sketchy. Verify us:

- 📅 **Book a call:** ${config.calendlyLink}
- 💬 **Join our Discord:** ${config.discordLink}
- 🐦 **Twitter:** ${config.twitterLink}
- 🌐 **Website:** ${config.websiteLink}
- 📦 **CLI source:** ${config.aibtcCliRepo}

This is AIBTC's mission: bring AI agents to Bitcoin.

## Not interested?

No worries - just close this PR. We won't follow up unless you engage.

---

*This PR was generated by Appleseed, our open-source distribution engine. [View source](${config.appleseedRepoUrl})*
`;
}

// =============================================================================
// Tier B Template (AI agent builders)
// =============================================================================

function tierBPRBody(
  username: string,
  repoName: string,
  personalizationHooks: string[],
  config: Config
): string {
  const hookText = personalizationHooks.length > 0
    ? ` - ${personalizationHooks[0]}`
    : "";

  return `Hey @${username}! 👋

Nice work on **${repoName}**${hookText}! We're reaching out to AI builders about the Bitcoin agent economy.

## One command. Wallet + Moltbot + yield.

\`\`\`bash
npx aibtc-cli install
\`\`\`

You'll get:
- **Stacks wallet** for Bitcoin L2
- **Moltbot** for AI agent capabilities
- **Auto-yield** on sBTC (~5% APY)

## Free sBTC

Reply with your Stacks address (starts with \`SP...\`) and we'll send you sBTC.

## Why?

Bitcoin is AI-native money. Your agents should hold, earn, and spend BTC - not stablecoins.

## Verify us

- 📅 ${config.calendlyLink}
- 💬 ${config.discordLink}
- 🌐 ${config.websiteLink}

Not interested? Just close this PR.

---

*Generated by [Appleseed](${config.appleseedRepoUrl}) - AIBTC distribution engine*
`;
}

// =============================================================================
// Tier C Template (Generic)
// =============================================================================

function tierCPRBody(
  username: string,
  repoName: string,
  _personalizationHooks: string[],
  config: Config
): string {
  return `Hey @${username}! 👋

We're inviting developers to try \`aibtc-cli\` - tools for AI agents on Bitcoin.

## Quick Start

\`\`\`bash
npx aibtc-cli install
\`\`\`

## Free sBTC airdrop

Reply with your Stacks address and we'll send sBTC.

## Learn more

- ${config.websiteLink}
- ${config.discordLink}

---

*Generated by [Appleseed](${config.appleseedRepoUrl})*
`;
}

// =============================================================================
// Export
// =============================================================================

/**
 * Generate PR body based on tier.
 */
export function generatePRBody(
  prospect: Prospect,
  personalizationHooks: string[],
  config: Config
): string {
  const tier = prospect.tier || "C";
  const repoName = prospect.targetRepo || prospect.repos[0]?.name || "your project";

  switch (tier) {
    case "A":
      return tierAPRBody(prospect.githubUsername, repoName, personalizationHooks, config);
    case "B":
      return tierBPRBody(prospect.githubUsername, repoName, personalizationHooks, config);
    case "C":
    case "D":
    default:
      return tierCPRBody(prospect.githubUsername, repoName, personalizationHooks, config);
  }
}

/**
 * Get file path for invitation file.
 */
export const INVITATION_FILE_PATH = ".github/AIBTC_INVITATION.md";
